wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.0
    start_time: 1658397622
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 4
      - 16
      4: 3.8.0
      5: 0.12.21
      8:
      - 3
      - 5
batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 2
gamma:
  desc: null
  value: 0.7
learning_rate:
  desc: null
  value: 1
